{
 "title": "CenturyLink C4000XG",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Internet Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(c4000xg_bytes_received{type=\"ethernet_vlantermination\"}[$__rate_interval])",
     "legendFormat": "Internet RX"
    },
    {
     "expr": "rate(c4000xg_bytes_sent{type=\"ethernet_vlantermination\"}[$__rate_interval]) * -1",
     "legendFormat": "Internet TX"
    }
   ]
  },
  {
   "title": "Client Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(hostname, mac_address) (rate(c4000xg_client_bytes_sent[$__rate_interval]))",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "sum by(hostname) (rate(c4000xg_client_bytes_received[$__rate_interval])) * -1",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "rate(c4000xg_bytes_sent{type=\"ethernet_interface\", name=\"eth0_1\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(c4000xg_bytes_received{type=\"ethernet_interface\", name=\"eth0_1\"}[$__rate_interval]) * -1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSSI (seen from AP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(hostname, mac_address) (c4000xg_client_signal_strength)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Signal to noise ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(hostname, mac_address) (c4000xg_client_x_ctl_snr)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "last_over_time(c4000xg_client_info[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disconnect rate (seen from AP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "max by(mac_address, hostname) (rate(c4000xg_client_x_gws_disconnect_count[$__rate_interval]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Clients per frequency band",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(frequency_band) (c4000xg_client_info{frequency_band!~\"..*\"})",
     "legendFormat": "Wired"
    },
    {
     "expr": "count by(frequency_band) (c4000xg_client_info{frequency_band=~\"..*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections per SSID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(ssid) (c4000xg_client_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "c4000xg_temperature", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Clients per wifi standard",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(wifi_standard) (c4000xg_client_info{wifi_standard!~\"..*\"})",
     "legendFormat": "Wired"
    },
    {
     "expr": "count by(wifi_standard) (c4000xg_client_info{wifi_standard=~\"..*\"})",
     "legendFormat": "802.11{{wifi_standard}}"
    }
   ]
  }
 ]
}